name: test
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install NPM dependencies
        run: npm install
      - name: Run tests
        run: npm run test
